### ISSUE TITLE
👋  Please stop spamming us with your errors

### ISSUE THREAD

**Issue by masylum** [robitec/hacktorial#1]
Hey there,

This is Pau from Factorial. Today we've noticed a lot of exceptions from `Hacktorial`.

![image](https://user-images.githubusercontent.com/28248/92161618-26346e80-ee31-11ea-9f52-2d53f63b8382.png)

It would be great if you can stop it, it's very annoying.

What are you trying to achieve? Can I help you?

(perhaps you find this interesting: https://chrome.google.com/webstore/detail/refactorial/enpfbnfeeibcaegponglcecbejcnboap?hl=es)

**Comment by maguri** [comment]
Hola Pau @masylum , 
Sorry, 🙏
I'm not using this code anymore for a long time ago,
I can neither confirm if this error is coming from this code or any other HTTPS request directly to your API.
